version: "3.9"

services:
    app:
      build:
        context: app
      ports:
        - "5000"
    
    nginx:
      image: nginx:latest
      volumes: 
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      ports:
        - "80:80"
      depends_on:
        - app